UK_COUNTY_NAMES = ['Bedfordshire',
'Berkshire',
'Buckinghamshire',
'Cambridgeshire',
'Cheshire',
'Cornwall',
'Cumbria',
'Derbyshire',
'Devon',
'Dorset',
'Durham',
'East Riding',
'East Sussex',
'East Yorkshire',
'Essex',
'Gloucestershire',
'London',
'Hampshire',
'Hertfordshire',
'Huntingdonshire',
'Kent',
'Lancashire',
'Leicestershire',
'Lincolnshire',
'Merseyside',
'Middlesex',
'Norfolk',
'Northamptonshire',
'Northumberland',
'Nottinghamshire',
'Oxfordshire',
'Rutland',
'Shropshire',
'Somerset',
'South Yorkshire',
'Staffordshire',
'Suffolk',
'Surrey',
'Tyne and Wear',
'Warwickshire',
'Westmorland',
'Wiltshire',
'Worcestershire',
'West Sussex',
'West Yorkshire',
'Anglesey',
'Blaenau Gwent',
'Bridgend',
'Cardiff',
'Caerphilly',
'Carmarthenshire',
'Cerdigion',
'Conwy',
'Denbighshire',
'Flintshire',
'Gwynedd',
'Merthyr Tydfil',
'Monmouthshire',
'Neath Port Talbot',
'Newport',
'Pembrokeshire',
'Powys',
'Rhondda Cynon Taff',
'Swansea',
'The Vale of Glamorgan',
'Torfaen',
'Wrexham',
'Aberdeen',
'Aberdeenshire',
'Angus',
'Argyll and Bute',
'Clackmannanshire',
'Dumfries and Galloway',
'East Ayrshire',
'East Dunbartonshire',
'East Lothian',
'Edinburgh',
'Eilean Siar',
'Falkirk',
'Fife',
'Glasgow',
'Highland',
'Inverclyde',
'Midlothian',
'Moray',
'North Ayrshire',
'North Lanarkshire',
'Orkney Islands',
'Perth and Kinross',
'Renfrewshire',
'Shetland Islands',
'South Ayrshire',
'South Lanarkshire',
'Stirling',
'The Scottish Borders',
'West Dunbartonshire',
'West Lothian']
